### ISSUE TITLE
Design Update: Bootstrap Refactor (Chef-Profile page)

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/chefconnect#31]
## ⚙️ Feature

> ##### Which feature is affected by this update?

Refactor chef.jsx Css with Bootstrap.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Make cards for each section.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="909" alt="Screen Shot 2022-01-08 at 4 45 46 PM" src="https://user-images.githubusercontent.com/68756038/148664812-c7e7d563-19f4-4d99-9a15-d90ad43d5e60.png">
<img width="841" alt="Screen Shot 2022-01-08 at 4 46 00 PM" src="https://user-images.githubusercontent.com/68756038/148664816-e22ba363-bf5b-484f-9ec8-c7049b48c1fe.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Refactor DishPictures to include photo carousel.
- [ ] Make sure app looks good on both mobile and desktop.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
