### ISSUE TITLE
Feature: User can add a profile picture.

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/chefconnect#43]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can upload a profile picture.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the user profile page, when user clicks the add photo button, they can upload a profile picture.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="448" alt="Screen Shot 2022-02-10 at 8 08 10 PM" src="https://user-images.githubusercontent.com/68756038/153536355-0e8aed0c-10e5-4b2b-aa4e-63b98df82b6c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to to add images table.
- [x] Update `data.sql` to add a default photo for guest.

### ☁️ Server

- [x] Update `server/index.js` to handle post request. 
- [x] Add a new file named 'uploads-middleware.js', and define a middleware for uploads.
- [x] Make a POST request, to route '/api/uploads'.use uploadsMIddleware as parameter.
- [x] Create a URL for the image by combining '/images' with req.file.filename.
- [x] Insert the 'caption' and 'url' into the 'images' table.
- [x] Respond with the inserted row data.
- [x] Catch any errors.
- [x] Test with HTTPie.
- [x] Make a GET request, to route '/api/images'.
- [x] Respond with the inserted row data.
- [x] Catch any errors.
- [x] Handle all errors and respond to the client.

### ⚡ Client

- [x] Create a component to handle file uploads.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
