### ISSUE TITLE
Feature: User can become chefs

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/chefconnect#48]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can make a chef profile page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is in the user profile page, they can register to make a chef profile page by clicking "make chef profile" button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="763" alt="Screen Shot 2022-04-14 at 4 51 31 PM" src="https://user-images.githubusercontent.com/68756038/163494736-321fbf77-4aa9-451d-82d6-84f8dbfda2e7.png">
<img width="474" alt="Screen Shot 2022-04-14 at 4 51 39 PM" src="https://user-images.githubusercontent.com/68756038/163494741-d99175ae-9053-47c2-9ae8-7810736b4fe5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle post request for chef registration
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for chef registration form, like the above wireframes. 
- [x] Update component to handle post request for chef registration. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
