### ISSUE TITLE
Feature: User can live message chefs.

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/chefconnect#65]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can live message chefs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks the message button in chef profile page, they can live message chefs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1223" alt="Screen Shot 2022-04-30 at 12 53 01 PM" src="https://user-images.githubusercontent.com/68756038/166120687-49e165ca-8408-472a-ade1-323b809d5bd7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install socket.io package.
- [x] Update `server/index.js` to require 'socket.io' and assign to variable 'io.'
- [x] Use 'on' method on 'io' object with event of 'connection' with a parameter of socket. 
- [x] Within the above function, use 'on' method on socket object with a parameter of 'msg.'
- [x] Within the above function, use 'emit' method on 'io' object with two arguments, 'chat message' and variable msg. 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to handle live messages within in ChefProfile component.
- [x] Update ChefProfile component to add live message button on the bottom of page.
- [x] On button click, show messaging container.
- [x] Add a form with Id of "live-message"
- [x] On form submit, use emit method on form object. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
